<?php

namespace Database\Seeders;

use App\Models\MovementType;
use Illuminate\Database\Seeder;

class MovementTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $types = [
            // main_type
            [
                'code' => 'patient_payment',
                'name' => 'Pago de Paciente',
                'description' => 'Pago recibido de un paciente por consultas o tratamientos',
                'category' => 'main_type',
                'affects_balance' => 1,
                'icon' => '💰',
                'color' => 'green',
                'is_active' => true,
                'order' => 1,
                'parent_type_id' => null,
            ],
            [
                'code' => 'professional_payment',
                'name' => 'Pago a Profesional',
                'description' => 'Liquidación de comisiones a profesionales',
                'category' => 'main_type',
                'affects_balance' => -1,
                'icon' => '👨‍⚕️',
                'color' => 'blue',
                'is_active' => true,
                'order' => 2,
                'parent_type_id' => null,
            ],
            [
                'code' => 'cash_opening',
                'name' => 'Apertura de Caja',
                'description' => 'Apertura de caja al inicio del día',
                'category' => 'main_type',
                'affects_balance' => 0,
                'icon' => '🔓',
                'color' => 'orange',
                'is_active' => true,
                'order' => 3,
                'parent_type_id' => null,
            ],
            [
                'code' => 'cash_closing',
                'name' => 'Cierre de Caja',
                'description' => 'Cierre de caja al final del día',
                'category' => 'main_type',
                'affects_balance' => 0,
                'icon' => '🔒',
                'color' => 'orange',
                'is_active' => true,
                'order' => 4,
                'parent_type_id' => null,
            ],
            [
                'code' => 'cash_control',
                'name' => 'Control de Caja',
                'description' => 'Auditoría o control de caja',
                'category' => 'main_type',
                'affects_balance' => 0,
                'icon' => '🔍',
                'color' => 'purple',
                'is_active' => true,
                'order' => 5,
                'parent_type_id' => null,
            ],
            [
                'code' => 'shift_handover',
                'name' => 'Entrega de Turno',
                'description' => 'Traspaso de caja entre turnos',
                'category' => 'main_type',
                'affects_balance' => 0,
                'icon' => '🔄',
                'color' => 'indigo',
                'is_active' => true,
                'order' => 6,
                'parent_type_id' => null,
            ],
            [
                'code' => 'shift_receive',
                'name' => 'Recibo de Turno',
                'description' => 'Recepción de caja de turno anterior',
                'category' => 'main_type',
                'affects_balance' => 0,
                'icon' => '📥',
                'color' => 'teal',
                'is_active' => true,
                'order' => 7,
                'parent_type_id' => null,
            ],

            // expense_detail
            [
                'code' => 'refund',
                'name' => 'Reembolso',
                'description' => 'Devolución de dinero a pacientes',
                'category' => 'expense_detail',
                'affects_balance' => -1,
                'icon' => '🔄',
                'color' => 'yellow',
                'is_active' => true,
                'order' => 1,
                'parent_type_id' => null,
            ],
            [
                'code' => 'office_supplies',
                'name' => 'Insumos de Oficina',
                'description' => 'Gastos en materiales de oficina',
                'category' => 'expense_detail',
                'affects_balance' => -1,
                'icon' => '📎',
                'color' => 'red',
                'is_active' => true,
                'order' => 2,
                'parent_type_id' => null,
            ],
            [
                'code' => 'medical_supplies',
                'name' => 'Insumos Médicos',
                'description' => 'Gastos en material médico y sanitario',
                'category' => 'expense_detail',
                'affects_balance' => -1,
                'icon' => '💉',
                'color' => 'red',
                'is_active' => true,
                'order' => 3,
                'parent_type_id' => null,
            ],
            [
                'code' => 'services',
                'name' => 'Servicios',
                'description' => 'Pago de servicios (luz, agua, internet, etc.)',
                'category' => 'expense_detail',
                'affects_balance' => -1,
                'icon' => '🔌',
                'color' => 'red',
                'is_active' => true,
                'order' => 4,
                'parent_type_id' => null,
            ],
            [
                'code' => 'maintenance',
                'name' => 'Mantenimiento',
                'description' => 'Gastos en mantenimiento y reparaciones',
                'category' => 'expense_detail',
                'affects_balance' => -1,
                'icon' => '🔧',
                'color' => 'red',
                'is_active' => true,
                'order' => 5,
                'parent_type_id' => null,
            ],
            [
                'code' => 'taxes',
                'name' => 'Impuestos',
                'description' => 'Pago de impuestos y cargas fiscales',
                'category' => 'expense_detail',
                'affects_balance' => -1,
                'icon' => '🏛️',
                'color' => 'red',
                'is_active' => true,
                'order' => 6,
                'parent_type_id' => null,
            ],
            [
                'code' => 'professional_payments',
                'name' => 'Pagos a Profesionales',
                'description' => 'Pagos varios a profesionales (no liquidaciones)',
                'category' => 'expense_detail',
                'affects_balance' => -1,
                'icon' => '👨‍⚕️',
                'color' => 'red',
                'is_active' => true,
                'order' => 7,
                'parent_type_id' => null,
            ],

            // Externos (no caja)
            [
                'code' => 'salary',
                'name' => 'Sueldos',
                'description' => 'Pago de sueldos y cargas laborales',
                'category' => 'expense_detail',
                'affects_balance' => -1,
                'icon' => '👥',
                'color' => 'orange',
                'is_active' => true,
                'order' => 80,
                'parent_type_id' => null,
            ],
            [
                'code' => 'tax',
                'name' => 'Impuestos (Externo)',
                'description' => 'Pago de impuestos fuera de caja',
                'category' => 'expense_detail',
                'affects_balance' => -1,
                'icon' => '🧾',
                'color' => 'red',
                'is_active' => true,
                'order' => 81,
                'parent_type_id' => null,
            ],
            [
                'code' => 'external_rent',
                'name' => 'Alquiler (Externo)',
                'description' => 'Pago de alquiler fuera de caja',
                'category' => 'expense_detail',
                'affects_balance' => -1,
                'icon' => '🏠',
                'color' => 'blue',
                'is_active' => true,
                'order' => 82,
                'parent_type_id' => null,
            ],
            [
                'code' => 'external_services',
                'name' => 'Servicios (Externo)',
                'description' => 'Pago de servicios fuera de caja',
                'category' => 'expense_detail',
                'affects_balance' => -1,
                'icon' => '💡',
                'color' => 'yellow',
                'is_active' => true,
                'order' => 83,
                'parent_type_id' => null,
            ],
            [
                'code' => 'other_expense',
                'name' => 'Otros Gastos',
                'description' => 'Otros gastos no categorizados',
                'category' => 'expense_detail',
                'affects_balance' => -1,
                'icon' => '📋',
                'color' => 'red',
                'is_active' => true,
                'order' => 99,
                'parent_type_id' => null,
            ],

            // income_detail
            [
                'code' => 'professional_module_payment',
                'name' => 'Pago Módulo Profesional',
                'description' => 'Pago recibido por módulo de profesionales',
                'category' => 'income_detail',
                'affects_balance' => 1,
                'icon' => '💳',
                'color' => 'green',
                'is_active' => true,
                'order' => 1,
                'parent_type_id' => null,
            ],
            [
                'code' => 'zalazar_balance_payment',
                'name' => 'Pago de Saldos Dra. Zalazar',
                'description' => 'Pagos de saldos de la Dra. Zalazar',
                'category' => 'income_detail',
                'affects_balance' => 1,
                'icon' => '💰',
                'color' => 'green',
                'is_active' => true,
                'order' => 2,
                'parent_type_id' => null,
            ],
            [
                'code' => 'correction',
                'name' => 'Corrección de Ingreso',
                'description' => 'Ajuste o corrección de ingresos',
                'category' => 'income_detail',
                'affects_balance' => 1,
                'icon' => '✏️',
                'color' => 'blue',
                'is_active' => true,
                'order' => 3,
                'parent_type_id' => null,
            ],
            [
                'code' => 'other_income',
                'name' => 'Otros Ingresos',
                'description' => 'Otros ingresos no categorizados',
                'category' => 'income_detail',
                'affects_balance' => 1,
                'icon' => '📋',
                'color' => 'green',
                'is_active' => true,
                'order' => 4,
                'parent_type_id' => null,
            ],

            // withdrawal_detail
            [
                'code' => 'bank_deposit',
                'name' => 'Depósito Bancario',
                'description' => 'Retiro para depósito en banco',
                'category' => 'withdrawal_detail',
                'affects_balance' => -1,
                'icon' => '🏦',
                'color' => 'orange',
                'is_active' => true,
                'order' => 1,
                'parent_type_id' => null,
            ],
            [
                'code' => 'expense_payment',
                'name' => 'Pago de Gastos',
                'description' => 'Retiro para pago de gastos',
                'category' => 'withdrawal_detail',
                'affects_balance' => -1,
                'icon' => '💸',
                'color' => 'orange',
                'is_active' => true,
                'order' => 2,
                'parent_type_id' => null,
            ],
            [
                'code' => 'professional_liquidation',
                'name' => 'Liquidación de Profesional',
                'description' => 'Retiro para liquidación a profesionales',
                'category' => 'withdrawal_detail',
                'affects_balance' => -1,
                'icon' => '👨‍⚕️',
                'color' => 'orange',
                'is_active' => true,
                'order' => 3,
                'parent_type_id' => null,
            ],
            [
                'code' => 'safe_custody',
                'name' => 'Custodia en Caja Fuerte',
                'description' => 'Retiro para guardar en caja fuerte',
                'category' => 'withdrawal_detail',
                'affects_balance' => -1,
                'icon' => '🔐',
                'color' => 'orange',
                'is_active' => true,
                'order' => 4,
                'parent_type_id' => null,
            ],
            [
                'code' => 'other_withdrawal',
                'name' => 'Otro Retiro',
                'description' => 'Otros retiros no categorizados',
                'category' => 'withdrawal_detail',
                'affects_balance' => -1,
                'icon' => '📋',
                'color' => 'orange',
                'is_active' => true,
                'order' => 5,
                'parent_type_id' => null,
            ],
        ];

        foreach ($types as $type) {
            MovementType::updateOrCreate(
                ['code' => $type['code']],
                $type
            );
        }
    }
}
