<?php

namespace Database\Factories;

use App\Models\Patient;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Payment>
 */
class PaymentFactory extends Factory
{
    public function definition(): array
    {
        return [
            'patient_id' => Patient::factory(),
            'payment_date' => now(),
            'payment_type' => 'single',
            'total_amount' => fake()->randomElement([5000, 8000, 10000, 15000]),
            'is_advance_payment' => false,
            'concept' => null,
            'status' => 'confirmed',
            'liquidation_status' => 'pending',
            'liquidated_at' => null,
            'income_category' => null,
            'receipt_number' => null, // auto-generated by boot()
            'created_by' => null,
        ];
    }

    public function single(): static
    {
        return $this->state(['payment_type' => 'single']);
    }

    public function packagePurchase(): static
    {
        return $this->state(['payment_type' => 'package_purchase']);
    }

    // Egresos: se registran como 'manual_income' con total_amount negativo.
    // 'expense' fue eliminado del enum en v2.6.0 y CashController fue actualizado acorde.
    public function negativeIncome(): static
    {
        return $this->state([
            'payment_type' => 'manual_income',
            'patient_id' => null,
            'total_amount' => -fake()->randomElement([5000, 8000, 10000]),
            'concept' => fake()->sentence(),
        ]);
    }

    public function refund(): static
    {
        return $this->state([
            'payment_type' => 'refund',
            'total_amount' => -fake()->randomElement([5000, 8000, 10000]),
        ]);
    }

    public function manualIncome(): static
    {
        return $this->state([
            'payment_type' => 'manual_income',
            'patient_id' => null,
            'concept' => fake()->sentence(),
        ]);
    }

    public function liquidated(): static
    {
        return $this->state([
            'liquidation_status' => 'liquidated',
            'liquidated_at' => now(),
        ]);
    }

    public function cancelled(): static
    {
        return $this->state(['status' => 'cancelled']);
    }

    public function withAmount(float $amount): static
    {
        return $this->state(['total_amount' => $amount]);
    }
}
